output_dir: outputs/LivingRoom-36282/classic
dataset:
  name: scenetex
  dist: 2.5
  center: [0.85963, 1.1377, -4.6706]
  prompt: "a classic style living room"
  mesh_file: /rhome/hli/workspace/Text2Tex/data/LivingRoom-36282/scene.obj
  image_size: 512

train:
  lr: 0.0002

model:
  model_id: stabilityai/stable-diffusion-2-depth
  depth_config: configs/depth_preprocessor_config.json
  guidance_scale: 9.
  diff_timestep: 50
  model_type: depth
  overlap_filter: 0.3
  unet_train: False
    
